### ISSUE TITLE
Confusion regarding use of "bar-1" instead of "bar+1"

### ISSUE THREAD

**Issue by adewdev** [yhilpisch/aiif#7]
Sir,

Here is the piece of code taken from the backtest_strategy method:

            state = self.env.get_state(bar)
            action = np.argmax(self.model.predict(
                        self._reshape(state.values))[0, 0])
            position = 1 if action == 1 else -1
            if self.position in [0, -1] and position == 1:
                if self.verbose:
                    print(50 * '-')
                    print(f'{date} | *** GOING LONG ***')
                if self.position == -1:
                    self.place_buy_order(bar - 1, units=-self.units)
                self.place_buy_order(bar - 1,
                                     amount=self.current_balance)
                if self.verbose:
                    self.print_net_wealth(bar)
                self.position = 1
            elif self.position in [0, 1] and position == -1:
                if self.verbose:
                    print(50 * '-')
                    print(f'{date} | *** GOING SHORT ***')
                if self.position == 1:
                    self.place_sell_order(bar - 1, units=self.units)
                self.place_sell_order(bar - 1,
                                      amount=self.current_balance)
                if self.verbose:
                    self.print_net_wealth(bar)
                self.position = -1
              
In this code the buy and sell order is being called with "bar-1". Should it be "bar+1" instead since the action was predicted using current "bar". If not, can you please clear my misunderstanding?

Thanks,
Debasish

**Comment by yhilpisch** [comment]
Where exactly is this piece of code from? Chapter? File?

**Comment by adewdev** [comment]
It is from the file main/code/tbbacktesterrm.py.

**Comment by yhilpisch** [comment]
The prediction is for self.bar. It is available already at self.bar - 1. Therefore, based on the prediction, the position is opened at self.bar - 1.
